{
 "title": "Materialize Example Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Kafka Sources",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sql_total_kafka_sources{}" }
   ]
  },
  {
   "title": "Total Postgres Sources",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "sql_total_postgres_sources{}" }
   ]
  },
  {
   "title": "Total Materialized Views",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "sql_total_materialized_views{}" }
   ]
  },
  {
   "title": "Materialize Cluster CPU %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "sql_replica_cpu_usage{}" }
   ]
  },
  {
   "title": "Materialize Replica Memory %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "sql_replica_memory_usage{}" }
   ]
  }
 ]
}